version: '3.4'

services:
  redis:
    image: redis:alpine
    hostname: redis-server
    container_name: in_memory_db
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - ./:/usr/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=password
      - REDIS_TLS=false
    ports:
      - "8145:8081"
    depends_on:
      - redis